#!/bin/sh
set -eu

self=$0
while [ -L "$self" ]; do
    link=$(readlink "$self")
    case "$link" in
        /*) self=$link ;;
        *) self=$(dirname -- "$self")/$link ;;
    esac
done
project_root=$(CDPATH= cd -- "$(dirname -- "$self")" && pwd -P)
binary=$(make -s -C "$project_root" launcher-binary)
exec "$binary" "$@"
